FROM node:8

WORKDIR /usr/src/app
COPY package*.json ./
COPY nodemon.json ./
COPY tsconfig.json ./

EXPOSE 80

CMD npm config set cache-min 9999999 \
    && npm install \
    && npm run build \
    && npm run start:dev